#!/usr/bin/env python

import Adafruit_DHT

from flask import Flask,render_template,request

app = Flask(__name__)

sensor = Adafruit_DHT.DHT11

pin = '4'

@app.route("/temp")

def temp():

    humidity,temperature = Adafruit_DHT.read_retry(sensor, pin)

    templateData = {

        'temperature' : temperature,

        'humidity' : humidity

}

    return render_template('main.html',**templateData)

if __name__ == "__main__":

    app.run(host='0.0.0.0',port=80)